### ISSUE TITLE
Add Tests

### ISSUE THREAD

**Issue by localhuman** [CityOfZion/neo-boa#10]
3 layers of tests would be nice
- First set of tests would simply load and compile all example files to see if any of them have compile errors

- Unit tests would test individual methods in the code base to make sure they do what they should be doing.

- Final set of tests would involve including `neo-python` and running compiled tests through the VM to see if their output is as expected.

**Comment by jordancoil** [comment]
Is typing out functions something that we are looking to do with the example files? I think it might satisfy the first layer of tests, or is the first layer compiling more in reference to compiling to .avm format?

**Comment by chisleu** [comment]
Compiling to .avm and testing that it doesn't break is #1, #2 is to unit test the compiler code. Final test is to take the compiled examples and run them in the MV to see if they work as function for regression / system tests.

I started this but haven't had time to make much progress. Please feel free to take it over. I see plenty of work to do.

**Comment by localhuman** [comment]
Tests for all functionality are now here: https://github.com/CityOfZion/neo-boa/tree/master/boa_test/tests
