### ISSUE TITLE
Neo 3x support

### ISSUE THREAD

**Issue by ajara87** [CityOfZion/neo-boa#120]
Hi team,

Are there any plan to update Neo-boa to Neo 3x? what is the current state of this topic? can I help with this issue? I would like to contribute with CoZ

Kind regards,

**Comment by ixje** [comment]
To my best knowledge there is currently no ongoing development for this. We very much welcome contributions to add Neo 3.x support.

**Comment by ixje** [comment]
Development for neo3 support is ongoing here: https://github.com/CityOfZion/neo3-boa
