### ISSUE TITLE
Built-in command line interface for neo-boa

### ISSUE THREAD

**Issue by devhawk** [CityOfZion/neo-boa#121]
While it is great that neo-boa can be used as a library for custom compilation tools as described in the [Usage section](https://github.com/CityOfZion/neo-boa#usage) of the readme, it seems like an unnecessary burden to force all developers to build their own compilation tool. Neo-boa should provide a command line interface so that a developer simply needs to call `neo-boa contract.py` from the command line to produce the contract.avm file

**Comment by ixje** [comment]
Fixed in v0.7.0
