### ISSUE TITLE
Generating incorrect hash for ABI file

### ISSUE THREAD

**Issue by EdgeDLT** [CityOfZion/neo-boa#132]
I am struggling to get the Visual DevTracker to recognize contracts compiled by the new release of neo-boa. I found at least one problem, the hash for the abi.json file is not being generated correctly.

https://github.com/CityOfZion/neo-boa/blob/33e8483d1b458318d7a93a7e23d00a2050b36cef/boa/code/module.py#L472

This should be generating a standard contract script hash, e.g `0xef7da354338b408e08dd0c278c2875741966670f`, computed with sha256 and ripemd160.

**Comment by ixje** [comment]
fwiw; it's also supported by `hashlib` even if it might now show directly with autocomplete; 
```python
import hashlib
hashlib.new('ripemd160', hashlib.sha256(file.read()).digest()).hexdigest()
```
