### ISSUE TITLE
Compiler add BigInteger support

### ISSUE THREAD

**Issue by jordanfung** [CityOfZion/neo-boa#17]
When importing the BigInteger,  the compiler report  'not sure what to do with line <boa.code.line.Line object at 0x104861400> '.

**Comment by localhuman** [comment]
You shouldn't need BigInteger. You can just use a regular integer

**Comment by jordanfung** [comment]
I was writing some code like 'int("123")', and the Compiler said 'NotImplementedError: [Compilation error] Built in int is not implemented'. 

so, how can I convert a str to int?

**Comment by localhuman** [comment]
There are no VM opcodes for type conversion, so that will not work.

Everything is ultimately a byte array in the Neo VM. If you have a string number in the VM, it will not represent what you think it does.

```
m = 3  # this is actually b'\x03'
mystr_number = '12'  # this is actually b'\x12', which evaluates to 12849

Notify(mystr_number)
```

**Comment by jordanfung** [comment]
got it, thx!
