### ISSUE TITLE
Issue with appending to a list

### ISSUE THREAD

**Issue by pythugg** [CityOfZion/neo-boa#23]
l = [1,2,3]
    l.append(5)

`[I 180102 11:50:35 EventHub:102] [test_mode][SmartContract.Execution.Fail] [e96952d0043006836c4d0057a68c9779af7073bd] [[[1, 2, 3], 5], None, 6]`

**Comment by localhuman** [comment]
I can also reproduce this.  Will have to see what change may have caused it...

**Comment by localhuman** [comment]
For some reason the changes in neo-python's `ExecutionEngine` which support the array append opcodes got missed in a merge to master and dropped out of development.  Anyways, they're there now: https://github.com/CityOfZion/neo-python/commit/fe2007c20276775842d63221beb1d5b65d44fd52

Try pulling from master and see if it works!

**Comment by pythugg** [comment]
woo, nice work!
