### ISSUE TITLE
Have Runtime.Notify accept multiple parameters

### ISSUE THREAD

**Issue by metachris** [CityOfZion/neo-boa#36]
Would be great if we could use `Runtime.Notify` with multiple parameters, like the original implementation: http://docs.neo.org/en-us/sc/fw/dotnet/neo/Runtime/Notify.html

**Comment by ixje** [comment]
you can do
```
params = ['hi', 'this', 'works']
Notify(params)
```

**Comment by metachris** [comment]
Oh, thanks @ixje! That is so helpful, we need to document this kind of stuff, will be very useful for newcomers!

Perhaps after finishing the first jsonrpc at neo-python, we can do a little documentation sprint ;)

**Comment by metachris** [comment]
Tested, and works.

For anyone interested, an example is here: https://github.com/metachris/coz-python-smart-contract-
workshop/blob/master/1-print.py

**Comment by ixje** [comment]
@metachris I'm documenting my `lessons learned` while working on a dApp. This will be put somewhere in the nearby future :)

**Comment by metachris** [comment]
awesome!

great place to start can be a blog post, and then we take all the pieces and add docs to neo-python, neo-boa and wherever else
