### ISSUE TITLE
Contract Create, Migrate, Destroy signature issues?

### ISSUE THREAD

**Issue by brianlenz** [CityOfZion/neo-boa#37]
It looks to me like the `Create`, `Migrate`, and `Destroy` functions in Contract.py have incorrect signatures. Specifically, I believe that `Create` and `Migrate` are missing the `name` argument, and `Destroy` has a superfluous `contract` argument that should be removed.

```
def Create(script, parameter_list, return_type, need_storage, version, author, email, description):
...
def Migrate(script, parameter_list, return_type, need_storage, version, author, email, description):
...
def Destroy(contract):
```

should be:

```
def Create(script, parameter_list, return_type, need_storage, name, version, author, email, description):
...
def Migrate(script, parameter_list, return_type, need_storage, name, version, author, email, description):
...
def Destroy():
```

Please correct me if I'm wrong, as I admittedly do not fully understand how exactly these methods are translated to the corresponding neo blockchain function invocations.

**Comment by brianlenz** [comment]
Here's our attempt at `Migrate`, but it's definitely not working:

https://github.com/NarrativeNetwork/tokensale-neo-smartcontract/blob/migrate-support/ico_template.py#L280

The process seems to just short out and return 0.

**Comment by tuanphung** [comment]
That's true. As compared to C# version:

https://github.com/neo-project/neo-devpack-dotnet/blob/master/Neo.SmartContract.Framework/Services/Neo/Contract.cs

`name` is missed in `Create` & `Migrate`. And `contract` param is redundant in `Destroy`.
I have tried to invoke Destroy without param, work properly.

**Comment by localhuman** [comment]
This is fixed now: https://github.com/CityOfZion/neo-boa/blob/master/boa/interop/Neo/Contract.py
