### ISSUE TITLE
Inconsistent representation of zero

### ISSUE THREAD

**Issue by tingwai-to** [CityOfZion/neo-boa#43]
There's an inconsistency in how zero is represented depending on if you directly assign a variable the value zero vs calculating the value zero by math operations.

Example code below shows how `delta = b''` and `z = bytearray(b'\x00')`.

Also, this can be a problem if someone tries to store (`Put`) the value of `delta`, they will end up storing nothing. So when getting the value back using `Get`, since `delta = b''`, they will think `delta` doesn't exist in Storage.
```python
def Main(operation, args):
    x = 1
    y = 1
    delta = x-y
    z = 0
    Log(delta)
    Log(z)

    delta_len = len(delta)
    z_len = len(z)
    Log(delta_len)
    Log(z_len)
```

Log:
```
...[a7ec498ddf57795336bb3c8843ca36d9ec96f772] [b'']  # delta
...[a7ec498ddf57795336bb3c8843ca36d9ec96f772] [bytearray(b'\x00')]  # z
...[a7ec498ddf57795336bb3c8843ca36d9ec96f772] [b'']  # delta_len
...[a7ec498ddf57795336bb3c8843ca36d9ec96f772] [b'\x01']  # z_len
```

**Comment by localhuman** [comment]
This should now be fixed in https://github.com/CityOfZion/neo-python/pull/244
