### ISSUE TITLE
[DynamicAppCall] stack frame misalignment

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-boa#45]
When using `DynamicAppCall`'s sometimes the altstack frame is misaligned when returning from the call. To elaborate, after a call like e.g. this
```
allowance = DynamicAppCall(token_contract, 'allowance', params)
```
It can happen that the last frame before returning from the call is not dropped from the [altstack](https://github.com/CityOfZion/neo-python/blob/master/neo/VM/ExecutionEngine.py#L130).

This seems to be a compiler byte code generation issue and does not always happen. I've discussed this with @localhuman and we're not sure yet where the root cause is. 

A solution I used for myself is to patch [VMToken.py](https://github.com/CityOfZion/neo-boa/blob/f9753d65f562e79cc3790ffa25b70d09f6b8bd1b/boa/code/vmtoken.py#L930-L934) to look like this:
```
        if pytoken.is_dynamic_appcall:
            # push the contract hash
            vmtoken = self.convert1(
                VMOp.APPCALL, py_token=pytoken, data=bytearray(20))

            self.insert1(VMOp.NOP)
            self.insert1(VMOp.NOP)
            self.insert1(VMOp.NOP)
            self.insert1(VMOp.FROMALTSTACK)
            self.insert1(VMOp.DROP)
            self.insert1(VMOp.NOP)
            return vmtoken
```
Note this was needed for _MY_ specific smart contract as I needed to patch all calls except one. The 3 `NOP`s make it easy to find in a hexeditor and thus manually patch where needed. The `FROMALTSTACK` `DROP` is used for removing the extraneous stackframe. This serves as a possible solution for those encountering the same issue.

Finally: [here](https://www.dropbox.com/s/0ejoq3n0jatfvv3/list_access_wrong.zip?dl=0) is a zip with files + a readme to reproduce the issue. Hopefully we can test this with the new compiler :)

**Comment by localhuman** [comment]
I think that the new compiler from python 3.6 fixes this issue, but you may need to test yourself.
