### ISSUE TITLE
Does the method "verify_signature" work when compiler SmartContract?

### ISSUE THREAD

**Issue by maiganne** [CityOfZion/neo-boa#57]
`
from boa.code.builtins import verify_signature

def Main(signature):
    return verify_signature(signature,b'\x03\xeb\x08\x81\xd1\xd6GT\xd5\x02U\xbf\x16\x07\x9e\xd6\xcb\xc3\x98$c\xa8\x90L\xb9\x19B+9\x17\x8b\xef?')

`
I compiler a SmartContract like this ,but when I invoke ,it always return False,Why?

**Comment by ixje** [comment]
Something tells me it's not functional atm, see: https://github.com/CityOfZion/neo-boa/blob/fde79d356972b7ad62cfcf0b4a3b4d1f4f3501e9/boa_test/example/blockchain/SignatureTest.py#L26

If you want to debug it, the `verify_signature()` call is processed in the VM here: https://github.com/CityOfZion/neo-python/blob/master/neo/VM/ExecutionEngine.py#L582

Which eventually puts your arguments in these calls to determine if validation passes or not
https://github.com/CityOfZion/neo-python-core/blob/master/neocore/Cryptography/Crypto.py#L157-L158

**Comment by maiganne** [comment]
thanks
Can you give me a example of Contract Authentication that can wiorks?

**Comment by localhuman** [comment]
See the feature request here: https://github.com/neo-project/neo/issues/213
