### ISSUE TITLE
either blockchain or header API issue

### ISSUE THREAD

**Issue by hi0001234d** [CityOfZion/neo-boa#72]
One of my smart contract has this code 

 ```
currentHeight = GetHeight()
 currentHeader = GetHeader(currentHeight)
 data = currentHeader.GetConsensusData(currentHeader)
```

Its giving me this error Exception: Could not load attribute GetConsensusData

I'm must admit that I'm using older version of private net while I'm using the latest version of neo python to build and deploy contract. Not sure how to get around this, my requirement right now is to stick to setup but if it helps can I upgrade all consesus nodes on my private net

**Comment by localhuman** [comment]
You should do either this:
`data = GetConsensusData(currentHeader)`

or this:
`data = currentHeader.ConsensusData`

**Comment by hi0001234d** [comment]
I tried that also, and now tried again but not working

When I try this 
`data = GetConsensusData(currentHeader)`

got this error 
Exception: Target method GetConsensusData not found

and when I tried this
data = currentHeader.ConsensusData

got this error 
Exception: Could not load attribute ConsensusData

**Comment by hi0001234d** [comment]
even tried 
`data = currentHeader.GetConsensusData`

but no luck throws error as below 
Exception: Could not load attribute GetConsensusData

**Comment by hi0001234d** [comment]
I think getting header object has some issue 

```
    currentHeight = GetHeight()
    currentHeader = GetHeader(currentHeight)

```

**Comment by hi0001234d** [comment]
Is it because sync not 100%?

[PrivateNet] Progress: 8734/9745

**Comment by localhuman** [comment]
are you importing it?
`from boa.interop.Neo.Header import GetConsensusData`

It works ok in the tests. https://github.com/CityOfZion/neo-boa/blob/master/boa_test/tests/test_block.py#L45

**Comment by hi0001234d** [comment]
No I wasn't but now did and worked, thanks
