### ISSUE TITLE
No module named boa.blockchain

### ISSUE THREAD

**Issue by TimRi91** [CityOfZion/neo-boa#84]
i want to build a smart contract with neo-python and in my sc i want to have this module:

`from boa.blockchain.vm.Neo.Storage import GetContext, Get, Put, Delete`
i installed neo-boa in my neo-python-venv but i still get:
`No module named boa.blockchain How can i get this module linked?`
How can i get this fixed?

**Comment by ixje** [comment]
Using the latest `neo-boa` try `from boa.interop.Neo.Storage import GetContext, Get, Put, Delete`

**Comment by TimRi91** [comment]
Okay thanks! that works! And by the way. To Put a key-value pair into the On-Chain-Storage, do i have to call `Put(GetContext, Key, Val)` ?

**Comment by ixje** [comment]
I'm not sure if `GetContext` can be supplied like that as an argument. What I do know for sure is;
```
context = GetContext()
Put(context, Key, Val)
```

**Comment by ixje** [comment]
also feel free to join us on Discord. There are many people there in specific development channels that can help you out and you're likely to get an answer faster than here.

**Comment by TimRi91** [comment]
Okay then i will try this one. Can you send me an inventation link?

**Comment by ixje** [comment]
https://discord.gg/wgfKcK
