### ISSUE TITLE
CheckWitness does not pass using RegisterAppCall

### ISSUE THREAD

**Issue by chris-poli** [CityOfZion/neo-boa#85]
### Current behavior

- What is the problem?

Contract A does not pass CheckWitness in Contract B using RegisterAppCall. 

**Contract A calling Contract B**

`Contract = RegisterAppCall('14b768f3303fb642dfebe7dee4f45550226a47c2', 'operation', 'args')`

    def Main(operation, args):

        trigger = GetTrigger()

        if trigger == Application():

            if operation == "test_script_hash":
                address_to = args[0]
                contract_hash = GetExecutingScriptHash()

                params = [contract_hash, address_to, 10000]

                Contract('transfer', params)

**Contract B method being called**

` def do_transfer(ctx, t_from, t_to, amount):`

    if amount <= 0:
        return False

    if len(t_to) != 20:
        return False

    if CheckWitness(t_from):

        if t_from == t_to:
            print("transfer to self!")
            return True

        from_val = Get(ctx, t_from)

        if from_val < amount:
            print("insufficient funds")
            return False

        if from_val == amount:
            Delete(ctx, t_from)

        else:
            difference = from_val - amount
            Put(ctx, t_from, difference)

        to_value = Get(ctx, t_to)

        to_total = to_value + amount

        Put(ctx, t_to, to_total)

        OnTransfer(t_from, t_to, amount)

        return True
    else:
        print("from address is not the tx sender")

    return False

**Result** - Printed to the console
`"from address is not the tx sender"`

### What should be happening

- I believe CheckWitness should be passing in contract B.

### Your environment

- OS: (Windows version/Linux distro/OSX version) 
Ubuntu 16.04
- neo-python version: (hint: use `np-prompt --version`)
neo-python v0.7.1
- Python version: (hint: `python -V`)
Python 3.6.5

**Comment by deanpress** [comment]
Wouldn't passing this open up to security risks? e.g. a malicious smart contract calling `do_transfer` without the user's knowledge

**Comment by chris-poli** [comment]
I haven't looked at this for awhile and very well may have misunderstood but i was hoping at the time, Contract A, would just be able to trigger ```do_transfer```, meaning it could be easily proven a smart contract is the one calling an operation on its own behalf. To give specific context and ignoring the larger scope, for a withdrawal, the smart contract would be able to send its own funds to another address by getting its script hash and calling this method.

As you said though, NEP-5.1 is solving some of these issues, it sounds like a great proposal!

**Comment by deanpress** [comment]
@chris-poli I see, that makes sense. This issue proposes the ability for smart contracts to send their own funds by adjusting how CheckWitness works. I believe you could also do this by calling NEO API's `GetCallingScriptHash()` method and then comparing the resulting script hash against the first argument?
