### ISSUE TITLE
Convert  byte array to number  ?

### ISSUE THREAD

**Issue by bachvtuan** [CityOfZion/neo-boa#95]
Hi,
I used function GetHeight from package from boa.interop.Neo.Blockchain
The lasted block height on my private net is 10541 and this is what I get when run this function bytearray(b',)')
I googled for a while but don't find any code to convert bytearray(b',)') = 10541
Please help !

**Comment by localhuman** [comment]
```
>>> int.from_bytes(b',)', 'little')
10540
```
